### ISSUE TITLE
Installing NVM V16

### ISSUE THREAD

**Issue by tanatc1256** [comp426-2023-spring/a00#1]
***Delete text above this line before you submit your issue. Place your issue information in the appropriate sections below.***

#### Description
I followed the instruction for a00-onboarding to the point where I need to download NVM. I did so using the cURL and checked the version. In the instruction, it says that I should see V16, but what I have is v18.

#### Screenshots
![Instruction](https://user-images.githubusercontent.com/69814826/212433955-872470fe-6da2-4555-8da7-ce7368bfe288.png)
![V18](https://user-images.githubusercontent.com/69814826/212433976-e7b586b2-8bb9-4da6-9560-1ae0e78de79f.png)

#### File (link)
N/A

#### Steps to reproduce
Following the steps (incorrectly?) from a00-onboarding (from Windows -> Linux) to the point where you need to download NVM.

#### Steps to resolve
May need to uninstall NVM and reinstall the correct version?

**Comment by StevenAMartin** [comment]
I'm on Mac got the same version v18.13.0 of NVM.

**Comment by cheestov** [comment]
I solved this issue.
type the command:
`$ nvm install 16.17.0 --lts`
nvm will install that version and set it to the default one to use automatically.

**Comment by jdmar3** [comment]
Once you have NVM installed, indeed you should be able to run `nvm install --lts` and it will either install the current Long Term Support version or upgrade from whatever Node version you are running. We'll look at this together on Thursday this week as well.

**Comment by StevenAMartin** [comment]
I ran that command and got the following:

`$nvm install --lts`

> Installing latest LTS version.
> v18.13.0 is already installed.


Should I force version 16.17.0?

**Comment by jdmar3** [comment]
I think I mentioned this in class last week, but no. You want to be running the LTS version, which is 18 right now.
