### ISSUE TITLE
NVM Installation on Mac

### ISSUE THREAD

**Issue by zhuoyu73** [comp426-2023-spring/a00#3]
#### Description
For the NVM Installation step in Assignment 00, I runned the curl command to install NVM. After I installed it, I tried to run "nvm install --lts" but it says "nvm: command not found." So I opened a new terminal and re-ran the command "nvm install --lts", but it still says "nvm: command not found."

#### Screenshots
<img width="570" alt="2023-01-19 17 18 35" src="https://user-images.githubusercontent.com/97497879/213819208-28b2abc8-0aab-4791-a679-aa68b0c702c1.png">
<img width="569" alt="2023-01-19 17 18 43" src="https://user-images.githubusercontent.com/97497879/213819254-8c643f41-9197-4f5e-9b67-9e4e8baf1eed.png">

#### File (link)
[https://github.com/nvm-sh/nvm#install--update-script](url)

**Comment by kpwhit** [comment]
Did you try closing and reopening your terminal window? There's a line after the installation command that says to do that, so that might fix your issue.

**Comment by zhuoyu73** [comment]
> Did you try closing and reopening your terminal window? There's a line after the installation command that says to do that, so that might fix your issue.

Yes I did, but it still says "nvm: command not found"

**Comment by kpwhit** [comment]
> > Did you try closing and reopening your terminal window? There's a line after the installation command that says to do that, so that might fix your issue.
> 
> Yes I did, but it still says "nvm: command not found"

Oh yeah, I see that in your original comment now. That's strange, that worked for me. I'm not sure.

**Comment by jdmar3** [comment]
Did you, by chance, try what it suggests in the output of the install script and in the instructions regarding sourcing the script? 

In the instructions, it says that the install script attempts to add the NVM location to your path: 

>Running either of the above commands downloads a script and runs it. The script clones the nvm repository to `~/.nvm`, and attempts to add the source lines from the snippet below to the correct profile file (`~/.bash_profile`, `~/.zshrc`, `~/.profile`, or `~/.bashrc`).
>
>```sh
>export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
>[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
>```

In the output, it similarly suggests that you can run that directly in your shell: 

![image](https://user-images.githubusercontent.com/2459227/214383848-6645b323-1c67-455a-99f4-5342e402a7e4.png)

It seems like you maybe did the first part (closing and reopening your shell) but not the second part. Try that.

If that works, then check to see if those lines were added to your resource/profile file, which are listed above. The things you will need to know are: 

1. What shell are you running? Bash or ZShell? 
2. Where is the resource file? (It should be in your home directory.)

**Comment by daqichen** [comment]
I have encountered this before with a Mac, the simple solution according to the stackoverflow discussion that worked for me at the time was using `brew` to install and specifying the directory for NVM as a global variable.

To verify the path for NVM:
```
echo $NVM_DIR
```

[Stackoverflow detailed solution](https://stackoverflow.com/questions/63757008/terminal-not-recognizing-nvm-after-installed-with-home-brew/63760780#63760780)

**Comment by daqichen** [comment]
@zhuoyu73 Just checking in to see if this issue has been resolved?

**Comment by zhuoyu73** [comment]
> @zhuoyu73 Just checking in to see if this issue has been resolved?

Yes! It seems that I forgot to load vim. Thank you so much for your help!
