### ISSUE TITLE
Clarification needed: [PATH OF CURL]

### ISSUE THREAD

**Issue by DidiQut** [comp426-2023-spring/a00#8]
Hi professor Martin,

I had a question when I followed the instruction to install the software. When I check for curl, the path is different from the instruction.

In the instruction, when I typed $ which curl, it would be in /usr/bin/curl. However, when I typed $ which curl in my computer, it would be in /Users/zhidizhang/opt/anaconda3/bin/curl. I did some research online to find a way to change the path, but I did not find a good answer to change it. I am wondering if I need to change the path of curl, and would you mind giving me some instructions on how to change the path of curl.

Best,
Zhidi

**Comment by daqichen** [comment]
@DidiQut Check out [the answer in this post](https://superuser.com/a/1726745) and see if it helps.
