### ISSUE TITLE
Runtime error: Unable to change directory into newly-cloned repository

### ISSUE THREAD

**Issue by parrepu** [comp426-2023-spring/a00#9]
#### What is happening?
I successfully set up and added the SSH key to my account and am currently working on finishing the assignment. I'm able to clone my repository successfully, but I can't change the directory into my newly-cloned repository (Step 9 under "Finish the assignment").

#### What does the error say is happening?
I copied the command ($ cd a00-GHUSERNAME) directly into my terminal, but it keeps outputting the same error (-bash: cd: a00-parrepu: No such file or directory).

#### What do you think the error means?
It doesn't recognize the file or directory I'm specifying through my username (parrepu). The following username should be my GitHub Username, so I don't know why the following is happening.

#### Command string
$ cd a00-parrepu

#### Code snippet & Error Log
(https://user-images.githubusercontent.com/69826257/220799158-f9557f11-7dd8-4756-ac85-c773c6053233.png)

#### Node.js version
v18.14.2

#### Operating system
Linux LAPTOP-LPCQT12R 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by daqichen** [comment]
@parrepu Have you tried `ls` to check what are the valid directories? And make sure you are `git clone` the accepted a00 repo not the parent a00 repo

**Comment by jdmar3** [comment]
Also use `pwd` to get the path to your current working directory. That information will help you.

**Comment by daqichen** [comment]
@parrepu Was this issue resolved? If so, please close the issue. Thanks!

**Comment by daqichen** [comment]
Closing this issue seeing that all your autograder tests has passed.

**Comment by parrepu** [comment]
> @parrepu Was this issue resolved? If so, please close the issue. Thanks!

Hey! I'm so sorry, but I just saw this. I was able to solve this issue during office hours a few weeks back. Thank you! 

Best, 

Praneeth Arrepu
